server:
  port: 8080
# mysql数据库
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${customer.datasource.driver-class-name}
      url: jdbc:mysql://${customer.datasource.host}:${customer.datasource.port}/${customer.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${customer.datasource.username}
      password: ${customer.datasource.password}
#  redis:
#    host: ${attend.redis.host}
#    port: ${attend.redis.port}
#    password: ${attend.redis.password}
#    database: ${attend.redis.database}

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${MYSQL_ADDRESS}/${MYSQL_DATABASE:springboot_demo}
#    username: ${MYSQL_USERNAME}
#    password: ${MySQL_PASSWORD}
#  mvc:
#    view:
#      suffix: .html
#      prefix: /

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.customer.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      customer:
        mapper: debug
        service: info
        controller: info
customer:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: customer
    # 设置jwt过期时间
    admin-ttl: 720000000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: itshuo
    user-ttl: 7200000
    user-token-name: authentication
  alioss:
    endpoint: ${attend.alioss.endpoint}
    access-key-id: ${attend.alioss.access-key-id}
    access-key-secret: ${attend.alioss.access-key-secret}
    bucket-name: ${attend.alioss.bucket-name}
  wechat:
    appid: ${attend.wechat.appid}
    secret: ${attend.wechat.secret}
